[package]
name = "web"
version = "0.1.0"
authors = ["Sorin Davidoi <sorin@sorin-davidoi.com>"]
edition = "2018"

[dependencies]
maud = { version = "0.22.2", default-features = false }
rocket = { version = "0.5.0-rc", default-features = false }
